name: themakerz
favicon: null
layout_spectrum: 0.2067854180932045
typography_spectrum: 0.32612265925854445
title: The Makerz Production Team
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8353360637556762
  lightness: 0.038199970265850425
  saturation: 0.8450921399053186
  rhythmicContrast: 0.7580924215726554
purpose: []
