name: themakerz
favicon: null
layout_spectrum: 0.76633
typography_spectrum: 0.5858
title: The Makerz Production Team
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dce0e6'
    - '#151515'
    - '#6a6970'
    - '#adabab'
    - '#474a4d'
  brandStrength: 0.8353360637556762
  lightness: 0.038199970265850425
  saturation: 0.8450921399053186
  rhythmicContrast: 0.7580924215726554
purpose: []
